---
title: "Data Conversations with Communities"
output: 
  html_document:
    theme: cerulean
    css: styles.css
    # toc: true
    # toc_depth: 4
    # toc_float: true
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
```

The MWI is intended to be used in partnership with communities.
Consider hosting data conversations to review the data with community members.
These conversations can engage communities, solicit their perspectives, and yield new insights for interpreting the data.

Here are a few tips to ensure respectful and fruitful data conversations:

-   If you are not with a community-based organization yourself, work with one that is trusted by the community.
    The community-based organization can help you to recruit participants and understand the community's values and preferences.

-   Community members are experts about their neighborhoods.
    Open the conversation with one or two introductory exercises to highlight their expertise (see the Guide to Data Chats below for examples).

-   Ask community members what mental wellness means to them.
    How do they define mental wellness?

-   Acknowledge there is mistrust of researchers among communities of color due to historical events.
    Frame the data conversations as a way to build trust with community members.
    Use a partnerships approach that focuses on mutual benefit to communities and you/your organization.

-   Help community members to see themselves in the data so that it seems less academic.
    Highlight ways that community members use data every day.\

-   Ensure that any materials you share are written in plain language and have images that reflect the local community.

-   Community members' time is valuable.
    Compensate them with gift cards, cash, or other incentives that they would appreciate.\

-   Be flexible when facilitating data conversations.
    Allow people to share their thoughts, even if it seems outside of scope of your project.
    This can reveal new insights about mental wellness and build trust by making communities feel heard.\

See the following resources for more tips and ideas:

-   [Guide to Data Chats: Convening Community Conversations About Data](https://www.neighborhoodindicators.org/sites/default/files/publications/Guide%20to%20Data%20Chats%E2%96%A1%20Convening%20Community%20Conversations%20about%20Data.pdf) by the Urban Institute and National Neighborhood Indicators Partnership

-   [Plain Language](https://www.plainlanguage.gov/about/definitions/) by the Plain Language Action and Information Network


<blockquote class="focus">The driving force behind the MWI is that equity delivered to historically marginalized populations will accrue to others and potentially catalyze movement toward social and racial justice. </blockquote>

