---
title: "Frequently Asked Questions"
output: 
  html_document:
    theme: cerulean
    css: styles.css
    # toc: true
    # toc_depth: 4
    # toc_float: true
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
```

#### Who can use the MWI?

The MWI is publicly available to anyone.
Users including (but not limited to) communities, researchers, state and federal agencies, non-profits, and policy makers can examine, quantify, and compare the factors influencing community-level wellness for each ZIP Code in the nation using the MWI.

------------------------------------------------------------------------

#### How are the measures and domains weighted?

Measures in the MWI have been assigned default weights, which will be applied if you do not customize the MWI.
The selection of these default weights was informed by a review of relevant literature and other health indices.
Default weights were assigned based on the findings of this review related to the relative importance of the three domains, then a weighting penalty was assigned to measures that are not race stratified and to those that are not geographically granular (data that are not available at the Census Tract, ZIP Code, or ZCTA level).
See the [Weighting Methods](https://raw.githubusercontent.com/mitre/hse-mwi/main/Documentation/Methods/Weighting_Methods.pdf){target="_blank"} document for more information about the assignment of default weights.

However, you can adjust the weights of the measures in the MWI to better align to your use case or community needs using the "Create Your Own MWI" feature of the tool.

------------------------------------------------------------------------

#### Does MITRE provide technical assistance to support use of the MWI?

The MWI Toolkit provides detailed information on how to use and modify the MWI.
You can contact the MWI team with questions at [socialjustice\@mitre.org](mailto:socialjustice@mitre.org){.email}.

------------------------------------------------------------------------

#### Can I adjust the MWI to fit my use or my community's needs?

Yes!
The MWI can be modified using the "Create Your Own MWI" feature of the tool in three different ways; you may: 1) add new measures and data sets, 2) remove measures, and 3) change the weight assigned to each measure.

------------------------------------------------------------------------

#### What is the difference between ZIP Codes and ZCTAs?

United States Postal Service (USPS) ZIP Codes were created to improve mail delivery service.
They are based on postal routes rather than defined geographic boundaries.

ZCTA stands for "ZIP Code Tabulation Area".
ZCTAs were created by the United States Census Bureau and are statistical entities with geographic boundaries analogous to the ZIP Codes used by the USPS for mail delivery routes.

In the MWI, the term "ZIP Code" refers to ZCTAs, which are used in the MWI and are represented in maps and plots.
In most cases the ZCTA is the same as the USPS ZIP Code for an area.
For more information on ZCTAs, please see [census.gov](https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html){target="_blank"}.

------------------------------------------------------------------------

#### What kind of technical infrastructure would I need to have in place to use the MWI?

To use the exploration features of the MWI, you will need a device that can connect to the Internet (such as a computer or tablet), Internet access, and an Internet web browser.
If you would like to customize the MWI using the "Create Your Own MWI" feature, you will need additional tools, which may include Microsoft Excel, R, RStudio.
Please see the [Create Your Own MWI](https://sjp.mitre.org/mwi){target="_blank"} page for more details.
